### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by nicholi** [trmcnvn/DigitalOcean.API#83]
New API sections yet to be integrated:
- [ ] Billing History
- [ ] Invoices

There is also a new Container Registry API, but it is listed as Private Beta.

**Comment by JoshClose** [comment]
I'm looking for the Container Registry API.

**Comment by JoshClose** [comment]
I submitted a pull request for the Container Registry API. https://github.com/trmcnvn/DigitalOcean.API/pull/93

**Comment by PoisnFang** [comment]
What about that api for Space?

**Comment by Nicholi** [comment]
> What about that api for Space?

I am not the maintainer, but the reason is likely that this library is for working with DigitalOcean's "native" API's described here: https://developers.digitalocean.com/documentation/v2/

Spaces is really it's own beast and likely rather complex. As it is a drop-in design equivalent to AWS's S3 API. Which is why everyone recommends you just use the S3 client library for your language, and modify the calling the domains. I've had no issues using the official [AWSSDK.S3](https://github.com/aws/aws-sdk-net) .NET library for spaces in my own projects.

**Comment by PoisnFang** [comment]
> use the S3 client library

Yeah that's what I did
